name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and analyze on SonarCloud
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }} # Put the name of your token here
        run: ./build-analyze.sh
        shell: bash
